{% set name = "cucumber-tag-expressions" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cucumber-tag-expressions-{{ version }}.tar.gz
  sha256: 83ce5fa87d1b37a690106aedf58a12d0d16758f38f73336f2c703e2bfe01d7db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - enum34
    - python >=3.6

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cucumber/tag-expressions-python
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
