{% set name = "cucumber-tag-expressions" %}
{% set version = "6.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e63a66a8df15e70a3b0908af98c4fe4f3910f6e0cd375ae230be6097f2ff8a81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cucumber/tag-expressions
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
