{% set name = "cucumber-tag-expressions" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cucumber-tag-expressions-{{ version }}.tar.gz
  sha256: 83a175e06449d7817c88446357ec3b6a336057c9e3264eb09db8449412d31d58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - invoke
    - python >=3.6

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cucumber/tag-expressions
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
