{% set name = "cucumber-tag-expressions" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cucumber-tag-expressions-{{ version }}.tar.gz
  sha256: e314d5fed6eebb2f90380271f562248fb15e18636764faf40f4dde4b28b1f960

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - invoke
    - enum34
    - python >=3.6

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cucumber/tag-expressions-python
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
