{% set name = "cucumber-tag-expressions" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cucumber-tag-expressions-{{ version }}.tar.gz
  sha256: 71823468f567726332b87f40530b27fc83b35daea6514f5cbb03f0533d96e5be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - enum34
    - python >=3.6

test:
  imports:
    - cucumber_tag_expressions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cucumber/tag-expressions-python
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
