schema_version: 1

context:
  name: cucumber-tag-expressions
  version: "8.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 4af80282ff0349918c332428176089094019af6e2a381a2fd8f1c62a7a6bb7e8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.9.0,<0.10.0
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - cucumber_tag_expressions
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/cucumber/tag-expressions

extra:
  recipe-maintainers:
    - thewchan
