schema_version: 1

context:
  name: cucumber-tag-expressions
  version: "7.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 3acb919113eb361930519f4280b23e1df58a0201b9512d25470a2e9eea8868ed

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - cucumber_tag_expressions
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/cucumber/tag-expressions

extra:
  recipe-maintainers:
    - thewchan
